### ISSUE TITLE
Как работает плагин реферальная ссылка?

### ISSUE THREAD

**Issue by lapsedisk** [evgeny-tc/dle-billing-module#10]
Как работает плагин реферальная ссылка? При переходе на /partner/admin выходит 404 ошибка

**Comment by evgeny-tc** [comment]
В файл .htaccess (в корне сайта), после:
`RewriteEngine On`
добавить:
`RewriteRule ^partner/(.*)(/?)+$ index.php?do=static&page=billing&seourl=billing&route=referrals/redirect&p=$1 [L]`

**Comment by lapsedisk** [comment]
Спасибо

**Comment by lapsedisk** [comment]
От другого пользователя открыл ссылку /partner/admin, просто белая страница. В реферальную страницу не добавляется его логин

**Comment by evgeny-tc** [comment]
В настройках плагина указана ссылка в поле "Редирект приглашенных пользователей", например: /index.php ?

Рефералы будут добавляться пользователю только после регистрации.

**Comment by lapsedisk** [comment]
Я указал страницу, редирект происходит. Зарегистрировался но в рефералах не появилась информация

**Comment by evgeny-tc** [comment]
Вас понял, обновитесь до версии 0.8.4

**Comment by lapsedisk** [comment]
Супер, спасибо! Теперь работает. Вопрос а партнёрские отчисления и там надо код указать это что? И у вас есть телеграмм? я бы хотел заказать подключение новой платёжной системы
