### ISSUE TITLE
Баг в плагине PayHide

### ISSUE THREAD

**Issue by lapsedisk** [evgeny-tc/dle-billing-module#12]
Добрый день! Нашел баг в PayHide. Прилагаю скрины:
![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/fdd7c888-c141-4268-927b-2cb58aea39e1)
![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/39b80c39-b06b-47db-9660-361d1c97128f)

Не выводит title у Оплаты доступа

**Comment by evgeny-tc** [comment]
[fix](https://github.com/evgeny-tc/dle-billing-module/blob/main/engine/modules/billing/install/_template_/billing/pay/waiting.tpl#L22)
