### ISSUE TITLE
Ошибка с платежной системой PayOk

### ISSUE THREAD

**Issue by lapsedisk** [evgeny-tc/dle-billing-module#13]
![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/c034b399-b43c-4f9a-84e1-6fa4f757a617)
После нажатия на платежную систему, вот такая ошибка

**Comment by evgeny-tc** [comment]
Можете обновиться до [0.8.5](https://github.com/evgeny-tc/dle-billing-module/commit/4886ac124f6837b03236b48d50b4c2a6ce5d006c)

**Comment by lapsedisk** [comment]
Спасибо
