### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by aqyl** [evgeny-tc/dle-billing-module#15]
Fatal error: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in почему выходит ошибка?

**Comment by evgeny-tc** [comment]
Какая страница, файл, действия при которых появляется ошибка?

**Comment by evgeny-tc** [comment]
[подробное описание бага](https://github.com/evgeny-tc/dle-billing-module/issues/16#issuecomment-1597730741)
