### ISSUE TITLE
[BUG] оплата скрытого текста 

### ISSUE THREAD

**Issue by heder68** [evgeny-tc/dle-billing-module#22]
**Описание**
После оплаты скрытого текста, в админ панели (в разделе "Оплата скрытого текста" - ссылка на страницу где оплачена, при переходе на нее возникает ошибка https://домен/%7C/index.php?newsid=8#pay-Hkd

И на странице после оплаты, в биллинге тоже так же.

Я не знаю, исправлена эта ошибка или нет в новых версиях 

У меня ⤵️
**Версия:**
 - DLE: 16.00
 - DLE-Billing:v.0.8.7.5

**Comment by evgeny-tc** [comment]
Исправлено в [обновлении](https://github.com/evgeny-tc/dle-billing-module/releases/tag/release-30-08)
