### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kantuza** [evgeny-tc/dle-billing-module#24]
**Описание**
Есть косяки по админке, а конкретно стили. 
В темном стиле адмники не видно букв в пользовательском соглашении.
Так же в разделе "статистика" есть траблы с темной темой.

Но самый главный косяк это то что если боковая панель уменьшена, то из нее постоянно торчит активная панель Dle Billing что сильно мешает обзору и закрывает некоторые элементы. ❤️

**Comment by evgeny-tc** [comment]
Исправлено в [обновлении](https://github.com/evgeny-tc/dle-billing-module/releases/tag/release-23-09)
