### ISSUE TITLE
[BUG] ошибка урл пользователя 

### ISSUE THREAD

**Issue by heder68** [evgeny-tc/dle-billing-module#25]
**Описание**
Обнаружен баг в урл пользователь: в системе dle16 при регистрации через социальные сети Гугл идет урл "Имя+ФИО"
Пример ссылка на профиль http://site.org/heder+long

В билинге при нажатии на пользователя который был зарегистрирован с помощью соц сетей ( пишет у вас нет разрешения)  я так понимаю биллинг не поддерживает знак "+" он заменяет его пробелом (%20)
http://site.org/heder%20long
![IMG_20231003_090130](https://github.com/evgeny-tc/dle-billing-module/assets/66062655/71336809-5817-49bd-8cfe-61ee1a99453e)
![IMG_20231003_090101](https://github.com/evgeny-tc/dle-billing-module/assets/66062655/dfd3b60d-eec1-46ac-b7ef-238359fecff8)

Проверить бы не плохо с другими симфолами
**Версия:**
 - DLE: 16
 - DLE-Billing:9.2

**Comment by evgeny-tc** [comment]
Исправлено в [обновлении](https://github.com/evgeny-tc/dle-billing-module/releases/tag/release-15-10)
