### ISSUE TITLE
[BUG] Ошибка при оплате с Юмоней

### ISSUE THREAD

**Issue by aeproject1** [evgeny-tc/dle-billing-module#27]
В новой версии DLE Billing. Если оплата прошла с юмоней но оплата не с кошелька а с карты. На юмоней приходит 1950 руб. и доступ к PayHide не открывается так как цена 2000 руб. Можете исправить чтобы он учитывал комиссию 20 или 40 руб. и открывался доступ. В 0.8.3 все отлично было в 0.9.3 ошибка!

**Comment by evgeny-tc** [comment]
Здравствуйте,

Включите [логирование](https://dle-billing.ru/doc/dev/payment/testmod) и попробуйте оплатить доступ (или пополнить баланс пользователя. 

Сообщите об ошибках в логе здесь

**Comment by evgeny-tc** [comment]
Исправлено в [обновлении](https://github.com/evgeny-tc/dle-billing-module/releases/tag/release-15-10)

**Comment by aeproject1** [comment]
Добрый день! Оказывается ошибка была на моей стороне. Я url обработчик неправильно указал в юмоней) Простите)
