### ISSUE TITLE
[BUG] Ошибка в новой версии DLE 17.0

### ISSUE THREAD

**Issue by aeproject1** [evgeny-tc/dle-billing-module#28]
В новой версии DLE не возможно пополнить баланс, выдает ошибку:
![image](https://github.com/evgeny-tc/dle-billing-module/assets/146417570/455fc2e1-dcfe-4d2f-97ed-4b653bda2615)

В .htaccess указал:
![image](https://github.com/evgeny-tc/dle-billing-module/assets/146417570/0871b606-45ff-4b03-8408-ddfa16deef4a)

В чем может быть ошибка?

**Comment by aeproject1** [comment]
Проблема в том что в адресную строку не добавляет: /billing.html/pay/waiting/id/284
А просто: /billing.html/pay/

![image](https://github.com/evgeny-tc/dle-billing-module/assets/146417570/0a5ed69e-cc00-4d48-a5bc-efc1b0e6514e)
![image](https://github.com/evgeny-tc/dle-billing-module/assets/146417570/7de63c2f-e5c0-4640-a5be-6dab2f47538f)

**Comment by evgeny-tc** [comment]
Проверено на новой версии dle 17.0 - проблем не обнаружено.

Смотрите файл .htaccess в корне сайта, часть с 
```
# billing
RewriteRule ^([^/]+).html/(.*)(/?)+$ index.php?do=static&page=$1&seourl=$1&route=$2 [QSA]
```

должна быть в самом конце файла
