### ISSUE TITLE
Ошибка в плагине PayHide

### ISSUE THREAD

**Issue by lapsedisk** [evgeny-tc/dle-billing-module#4]
После покупки пишет что скрытый текст куплен. В billing.html тоже показывает что доступ открыт. Но в fullstory.tpl показывается всю равно close.tpl

Использую вот такой тег:
```
[payhide key=fgh price=1500 time=43200]
<h2>Привет мир!</h2>
[/payhide]
```

Скриншоты:
![Screenshot_2](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/e7390343-5d09-42e6-a2e5-b9cff2a5d3aa)
![Screenshot_1](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/5a1ab71b-13aa-418b-bbf6-1c19d117f185)

**Comment by evgeny-tc** [comment]
Попробуйте указать цену с дробной частью:

`[payhide key=fgh price=1500.00 time=43200]`

**Comment by lapsedisk** [comment]
Супер, теперь работает! Спасибо большое за прекрасный, удобный модуль!
