### ISSUE TITLE
[BUG] Нет платежных систем

### ISSUE THREAD

**Issue by exforex** [evgeny-tc/dle-billing-module#41]
**Описание**
Описание ошибки.
При пополнении баланса или при оплате не отображаются платежные системы. см. скриншоты.
В настройках модуля активированы две платежные системы: ЮМани и FreeKassa.
Сначала подумал, может проблема в моем шаблоне.
Перенес всё на шаблон Default.
Та же картина, платежные системы не отображаются...

**Как быть?**

![2024-01-31_09-53-53](https://github.com/evgeny-tc/dle-billing-module/assets/99262220/592aa950-c3f2-4971-9de9-39acc25067c9)
![2024-01-31_11-27-26](https://github.com/evgeny-tc/dle-billing-module/assets/99262220/11ce5808-d9e9-4a46-8866-6984b6f96707)

**Версия:**
 - DLE: 17
 - DLE-Billing:0.9.5
 - PHP:8.3

**Comment by evgeny-tc** [comment]
Проверьте, что бы в настройках платежной системы были заполнены настройки "Минимальная сумма платежа" и "Максимальная сумма платежа". 
Сумма по квитанции должна входить в эти промежутки, иначе платежная система не выводится.

**Comment by exforex** [comment]
Спасибо большое!
Помогло.
Если можно еще пара вопросов:
1. Как вывести название валюты из настроек модуля в шаблон закрытой информации (closed.tpl)? (см. скриншот). Пришлось в шаблоне прописать **USD** (как в настройках) вместо **РУБ**. Хотелось бы чтобы это бралось из настроек... Возможно и для других плагинов это потребуется, еще не проверял, но тут сразу столкнулся с этим...
2. Как в этот же шаблон вывести баланс пользователя? Я сделал вывод через "**одно место**", но было бы лучше, чтобы это можно было выводить с помощью модуля. Конструкция типа `{include file="engine/modules/billing/widgets/balance.php"} `выводит эту строку **{include file="engine/modules/billing/widgets/balance.php"}**
![2024-02-01_10-44-59](https://github.com/evgeny-tc/dle-billing-module/assets/99262220/c7415e43-cec9-425b-9edc-329dcab6d36b)

**Comment by evgeny-tc** [comment]
1,2 - в модуле такого функционала нет, запишу в план-лист на след.версии

3 - можете внести правки напрямую в файл с настройками платежной системы /engine/data/billing/payment.{name}.php:

`'convert' => "1",`

**Comment by exforex** [comment]
> 1,2 - в модуле такого функционала нет, запишу в план-лист на след.версии
> 
> 3 - можете внести правки напрямую в файл с настройками платежной системы /engine/data/billing/payment.{name}.php:
> 
> `'convert' => "1",`

1,2 - спасибо. Будет здорово и удобнее.

3 - Правки напрямую в файл помогли, но думаю нужно как-то предусмотреть этот момент для будущих версий.

Я пытаюсь подключить платежную систему Perfect Money, но что-то не получается. Вернее работает так:
Платеж на стороне ПС обрабатывается нормально. Но когда после оплаты в ПС нажимаю на кнопку чтобы вернуться на сайт, возвращаюсь как неавторизованный пользователь. Квитанция остается неоплаченной и средства на баланс не зачисляются. В логах, соответственно, ничего нет. Я так понимаю что не доходит даже до **public function check_out(...**
Я могу вам как-то передать свою реализацию ПС чтобы вы посмотрели и указали мне на возможные ошибки?

**Comment by evgeny-tc** [comment]
Проверьте, что в платежной системе правильно указан "URL обработчика платежей" из настроек модуля.
Запись в лог должна быть независимо от реализации check_out и других методов.

**Comment by exforex** [comment]
Здравствуйте, Евгений!

Проверил.
"URL обработчика платежей" в настройках платежной системы указан верно.

Perfect Money требует чтобы в форме были указаны адреса на который отправляется ответ от ПС при удачном исходе операции и при неудачном, используя 1 из вариантов LINK | POST | GET.
Если указать "billing.html/pay/ok" в качестве удачной оплаты с любым из вариантов (LINK | POST | GET) и "billing.html/pay/bad" для неудачной оплаты, тоже с любым из вариантов (LINK | POST | GET), то оплата проходит только на стороне платежной системы и квитанция остается неоплаченной. В логах тоже ничего нет.
Если указать для удачной и неудачной операции "URL обработчика платежей", то средства зачисляются на счет и в логах тоже есть информация, что все ОК.
Однако возврат с платежной системы происходит на "URL обработчика платежей", причем так как буд-то на сайте я не авторизован... После обновления страницы и подтверждения что нужно обновить страницу, я снова в своем аккаунте без ввода логина и пароля и платеж проводится.
Да и к тому же, я думаю, что неверно указывать в форме для ПС "URL обработчика платежей", ведь в нем содержится секретный код ("Ключ доступа платежной системы").
Я могу здесь загрузить мой файл "adm.settings.php" чтобы вы посмотрели? Или здесь выложить код файла?

Заранее благодарю за помощь!
С уважением, Олег.

**Comment by evgeny-tc** [comment]
Если Perfect Money не позволяет указать "URL обработчика платежей" в личном кабинете, не передавая его в форме в открытую - то тут нечего не поделаешь: либо передавать в открытую, либо написать свой обработчик.

**Comment by exforex** [comment]
"...либо написать свой обработчик..." - может есть примеры реализаций такого обработчика, чтобы можно было прикрутить к DLE Billing ? Или любые подсказки по реализации?..

**Comment by evgeny-tc** [comment]
Нет, примеров нет

**Comment by exforex** [comment]
Добрый день, Евгений!
С URL решил вопрос через JS. Передаю его только во время отправки формы на сайт ПС.
Меня всё мучает проблема того, что при возврате с платежной системы после оплаты, я попадаю на сайт как неавторизованный и нужно обновить страницу чтобы платеж был зачислен. В качестве адреса при успешной оплате установлен "URL обработчика платежей", по другому не проходят платежи, но даже если установить другой URL (любой), то всё равно, возвращаюсь с ПС как неавторизованный.
Посмотрите, пожалуйста, логи в аттаче. Может подскажете что не так?
[Logs PM.txt](https://github.com/evgeny-tc/dle-billing-module/files/14161925/Logs.PM.txt)

**Comment by exforex** [comment]
Евгений, добрый день!
И извините, что, может быть, достал вас своими вопросами, но очень надо!...
Если со своей реализацией оплаты через Perfect Money кое-как разобрался и всё работает нормально, то с ЮMoney беда...
Обнаружил баг в ПС ЮMoney.
Настраивал систему, делал тестовые платежи, небольшими суммами, в результате на стороне ПС все ОК, деньги с плательщика списываются и получателю зачисляются (удерживая комиссию платежной системы).
А вот на сайте на баланс пользователя ничего не зачисляется и квитанция остается неоплаченной.
Посмотрел логи и увидел следующую картину:
![2024-02-06_16-42-12](https://github.com/evgeny-tc/dle-billing-module/assets/99262220/a491a998-8149-4999-b056-57dcf21ed143)

Получается, чтобы на сайте платеж был обработан, нужно включать комиссию ЮMoney, в квитанцию или при получении ответа от платежной системы?
Не подскажете где и как это можно подправить?
Квитанция была выписана на сумму 2.74, а ответ от ПС пришел 2.71 с учетом удержанной комиссии...

**Comment by exforex** [comment]
Евгений, еще раз здравствуйте!
Ошибка по последнему вопросу решена.
Проблема была в том, что для конвертации валюты сайта и валюты ПС я получаю данные по курсам валют с сайта ЦБРФ, а там после точки 4 знака. Например: **1 USD = 90.6842**, а сумма в **$data['withdraw_amount']** приходила с двумя знаками после точки. Округление значения **$invoice['invoice_pay']** до двух знаков решило проблему.
Надеюсь, что вопросами пока вас мучить больше не буду.
И хочу поделиться с вами платежной системой Perfect Money, если вам это нужно.
Подскажите как я могу это сделать?
Здесь я не очень ориентируюсь как добавить к вашему проекту ПС.
Может вам на почту прислать?
Спасибо еще раз за ваши ответы и за помощь!
С уважением, Олег.
