### ISSUE TITLE
[BUG] палагин paygroups

### ISSUE THREAD

**Issue by 6ashmak** [evgeny-tc/dle-billing-module#42]
**Описание**
При оплате перехода в группу, в лог заносится не дата до которой куплен переход, а текущая дата.
Например вот что в логе сейчас вывелось при покупке на 60 дней: Оплата перехода в группу VIP на 60 дн. до 01.02.2024 19:20
Т.е. текущая дата на примере выше.

**Версия:**
 - DLE: 17
 - DLE-Billing: 0.9.4
 - PHP: 8.1

**Comment by evgeny-tc** [comment]
Спасибо

Исправлено в [коммите](https://github.com/evgeny-tc/dle-billing-module/commit/d9d80fd36635348adf3fb357a13f49b75e1bbf82) 

Можете внести правки в файл в ручную или подождать обновления модуля
