### ISSUE TITLE
[BUG] FreeKassa

### ISSUE THREAD

**Issue by mondidub** [evgeny-tc/dle-billing-module#51]
**FreeKassa стала com**
Не переходит на страницу оплаты.
Поменял ru на com в adm.settings 83 строке
`<form method="get" action="https://pay.freekassa.COM/" accept-charset="UTF-8" id="paysys_form">`
Появилась страница оплаты, но оплата не проходит не в тестовом режиме, ни в каком.
Уже на странице оплаты вижу такую ошибку
![image](https://github.com/user-attachments/assets/380d245a-acf6-44b7-a1c3-f50bec966acf)
Когда жмешь оплатить ошибка повторяется
![image](https://github.com/user-attachments/assets/e3acb8c3-21f5-4f30-bf14-c82a5b1981f6)
Все настройки верны. Смущает только, что в настройках кассы есть api, а в плагине нету.
![image](https://github.com/user-attachments/assets/1cad966d-dc16-4da5-85ee-b45fb01477c1)
![image](https://github.com/user-attachments/assets/1dbf5dfe-b45c-4679-84ea-f4c96ba6c780)
В какой-то момент стала вылезать такая ошибка
![image](https://github.com/user-attachments/assets/cedb2686-d858-4253-b9f3-e6533687e179)
![image](https://github.com/user-attachments/assets/06a31437-677f-46cd-b4c4-62d9f7a8958f)

**Версия:**
 - DLE: 17.0
 - DLE-Billing: 0.9.5
 - PHP: 8.1.2

**Comment by lazyphpdev** [comment]
Нужно обновить секретные ключи.

**Comment by mondidub** [comment]
> Нужно обновить секретные ключи.

Да, обновил - заработало. Забыл написать.
