### ISSUE TITLE
Не загружает картинку balance.png

### ISSUE THREAD

**Issue by lapsedisk** [evgeny-tc/dle-billing-module#7]
Не загружает картинку balance.png когда хочу оплатить с баланса. Неправильный путь до картинки. У платежных систем картинки работают

Второй баг: В квитанциях в billing.html не работает кнопка удаления

А так модуль отличный! Спасибо вам! 

Идея по улучшению модуля: добавить в настройках модуля функцию выключения квитанций. Иногда квитанции не нужны)

**Comment by evgeny-tc** [comment]
Добавил иконки в 0.8.3, можно обновиться.
