### ISSUE TITLE
При установки модуля выводится ошибка

### ISSUE THREAD

**Issue by lapsedisk** [evgeny-tc/dle-billing-module#9]
При установки модуля выводится ошибка

![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/69eea32e-0681-44cf-a594-1357690fc007)

И при пополнении баласна тоже выводится ошибка:

![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/fd056733-b76b-4030-b4a0-041bdc4528bc)

**Comment by evgeny-tc** [comment]
Какая версия модуля и php?

**Comment by lapsedisk** [comment]
Сейчас установил новую версию вашего модуля 0.8.3. Установка прошла успешна а вот у пополнения баланса ошибка:

![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/fff510d8-20c9-4539-945a-432889a4402b)

**Comment by evgeny-tc** [comment]
Я вас понял, попробуйте обновить до 0.8.3.1 или внести [правки](https://github.com/evgeny-tc/dle-billing-module/commit/e052b334a04bf69236acc996f3e0313843fe07dd) в файл самостоятельно

**Comment by lapsedisk** [comment]
Супер, теперь работает. И еще один баг

Баланс 3500, но пишет что недостаточно. Но если сделать 3501 то покупает

![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/0b0b9db3-00b9-458b-9a53-b1912bc21e97)

**Comment by evgeny-tc** [comment]
Попробуйте [этот](https://github.com/evgeny-tc/dle-billing-module/commit/d7ee3951e9c1ae094e4cf5b4654986ccb34a1fa4) фикс

**Comment by lapsedisk** [comment]
Отлично, работает! Спасибо вам большое

**Comment by lapsedisk** [comment]
И еще вопрос: В квитанциях кнопка удаления не работает. В чем может быть ошибка, к какому классу оно присоединятеся?

![image](https://github.com/evgeny-tc/dle-billing-module/assets/134724835/69c421d3-865c-4599-8a23-3cd24b79aa94)
